### ISSUE TITLE
Exception: Serialization of 'Closure' is not allowed hybridauth linkedin  

### ISSUE THREAD

**Issue by karthikeyan-manivasagam** [joearcher/Phalcon-Hybridauth#1]
Error when linkedIn fails and show this Exception: Serialization of 'Closure' is not allowed

**Comment by karthikeyan-manivasagam** [comment]
Fixed it by these steps
http://monkpal.com/exception-serialization-closure-not-allowed-hybridauth-linkedin-phalcon

**Comment by joearcher** [comment]
Hi This appears to be an issue with HybridAuth, please submit this to their repository as a pull request.

Thanks.
